---BugSpeak v0.2.1 by @ceriole
---Loosely based upon KorboSpeak by @korbosoft

---Please do not edit this file unless you know what you are doing.

--- This is to prevent abuse/annoyance from trying to play too many sounds at once.
local SAFE_SPEECH_LENGTH = 64
-- This is to prevent the tokenizer from freaking the heck out.
local MAX_PHRASE_LENGTH = 16


---@class RunLater
---@author @manuel_2867
---@author @ceriole
---@field tmrs RunLater.Timer[]
---@field t number
local RunLater = {tmrs={}, t=0}

---@alias RunLater.predicate fun(): boolean

---@class RunLater.Timer
---@author @ceriole
---@field t number|false
---@field p RunLater.predicate|number
---@field n function

---Schedules a function to run after a certain amount of ticks
---@param ticks number|RunLater.predicate Amount of ticks to wait, or a predicate function to check each tick until it returns true
---@param next function Function to run after amount of ticks, or after the predicate function returned true
function RunLater.add(ticks, next)
	if not next then return end
    local is_delay= type(ticks) == 'number'
    table.insert(RunLater.tmrs, {
		t = is_delay and RunLater.t + ticks,
		p = is_delay and function()end or ticks,
		n = next
	})
end

---RunLater tick function. Runs functions added by RunLater.add.
---@see RunLater.add
function RunLater.tick()
    RunLater.t = RunLater.t+1
    for key,timer in pairs(RunLater.tmrs) do
        if timer.p() or (timer.t and RunLater.t >= timer.t) then
            timer.n()
            RunLater.tmrs[key]=nil
        end
    end
end

local function isImmediateChild(name, prefix)
	prefix = prefix:gsub("%.+$", "")
	if prefix ~= "" then
		if name:sub(1, #prefix) ~= prefix then
			return false
		end
		local after = name:sub(#prefix + 1)
		return not after:find("%.")
	end
	return not name:find("%.")
end

local function getAllSoundsMatchingPrefix(prefix)
	-- remove trailing dots.
	prefix = prefix:gsub("%.+$", "")
	local found = {}
	for _, sound in ipairs(sounds:getCustomSounds()) do
		if isImmediateChild(sound, prefix) then
			table.insert(found, sound)
		end
	end
	return found
end

---@alias Speech.SpeechCallback function<string, Sound?> callback function that runs whenever a speech sound is played. Can be used for custom visualizers or other effects. Set by Speech:setCallback.

---Speech object.
---@class Speech
---@field private sounds table<string, Sound[]> A list of sound resources. Use mono channel sounds, otherwise they will be heard globally!
---@field private phrases table<string, Sound[]> A list of phrases to play. Use mono channel sounds, otherwise they will be heard globally!
---@field private rate integer Rate of speech, how many ticks to wait per speech sound.
---@field private volume number Volume of speech sound.
---@field private basePitch number The base pitch to start at. nil = 1.0
---@field private pitchRange number Range of pitch randomization. Zero or nil disables random pitch.
---@field private maxLength integer Maximum amount of text characters to speak.
---@field private polyphony boolean Set to true if you want speech sounds to overlap.
---@field private subtitleVerb string The subtitle to display when this character speaks and somone hears it.
---@field private spacesPause boolean If true, pause self.rate ticks whenever spaces are encountered.
---@field private tellEnabled boolean If false, do not trigger speech for `/tell`, `/msg`, or `/w` commands.
---@field private append boolean If true, calling Speech:play will append the message to the `self.queue`. If false, every call of Speech:play will replace the current `queue`.
---@field private queue string[] The list of currently playing characters/phrases.
---@field private currentSound Sound The currently playing sound object.
---@field private speechCallback Speech.SpeechCallback A callback function that runs whenever a speech sound is played. Can be used for custom visualizers or other effects.
local Speech = {}
Speech.__index = Speech

---Creates a new speech object.
---@param o? table Optional table to initialize as the speech object.
---@return Speech speech The created speech object.
function Speech.new(o)
    o = o or {}
    setmetatable(o, Speech)
	o.sounds = {}
	o.phrases = {}
	o.rate = 1
	o.volume = 1
	o.basePitch = 1
	o.pitchRange = 0.25
	o.maxLength = SAFE_SPEECH_LENGTH
	o.polyphony = false
	o.subtitleVerb = 'speaks'
	o.spacesPause = true
	o.tellEnabled = true
	
	o.queue = {}
	o.currentSound = nil

	o.speechCallback = nil
    return o
end


---@alias SpeechSound string|Sound
---@alias SpeechSoundList SpeechSound[]
---@alias SpeechSoundMap table<string|number, SpeechSound|SpeechSoundList>

---Add a single sound to speech table. Prefer using addSound or addSoundSet, which internally use this function.
---
---@return self
---@param sound SpeechSound The speech sound to map.
---@param chars string? (Optional) If empty or nil, adds it to generic sounds. Otherwise maps the sound to every character in the string.
---@see Speech.addSound
---@see Speech.addSoundSet
function Speech:registerSound(sound, chars)
	chars = chars or ''
	if type(chars) ~= 'string' then
		error('registerSound(): illegal mapping argument: "'..tostring(chars)..'"')
		return self
	end
	if type(sound) ~= 'string' and type(sound) ~= 'Sound' then
		error('registerSound(): illegal sound argument: "'..tostring(sound)..'"')
		return self
	end

	if type(sound) == 'string' then
		local s = sounds[sound]
		if type(s) ~= 'Sound' then error('registerSound(): Sound "'..tostring(s)..'" is not a sound resource or string.') return self end
		sound = s
	end

	if #chars > 0 then
		chars = chars:lower()
		for c in chars:gmatch('.') do
			if not self.sounds[c] then self.sounds[c] = {} end
			table.insert(self.sounds[c], sound)
		end
	else
		if not self.sounds[''] then self.sounds[''] = {} end
		table.insert(self.sounds[''], sound)
	end

	return self
end

---Add one or more sounds as a string or Sound resource.
---
---String keys in mapping tables are treated as character groups.
---
--- Advanced mapping Example:
--- ```lua
--- { 
--- 	["aeiou"] = {"voices.vowel1", "voices.vowel2"}, -- Randomized vowel1/2 for all vowels
--- 	["!?"] = "click", -- "click" sound for both ! and ?
--- 	"fallback" -- fallback sound
--- }
--- ```
---
---@param sound SpeechSound|SpeechSoundList|SpeechSoundMap The sound resource(s) or sound path(s) to add.
---@return self
---@see sounds
---@see Sound
function Speech:addSound(sound)
	if type(sound) == 'string' or type(sound) == 'Sound' then
		self:registerSound(sound)
	elseif type(sound) == 'table' then
		for key, s in pairs(sound) do
			if type(key) == 'number' then key = nil end
			if type(s) == 'table' then
				for _, v in pairs(s) do
---@diagnostic disable-next-line: param-type-mismatch
					self:registerSound(v, key)
				end
			else
---@diagnostic disable-next-line: param-type-mismatch
				self:registerSound(s, key)
			end
		end
	end
	return self
end

---Add one or more sounds from the custom sound list using a `prefix`.
---@param prefix string The prefix to search for in the custom sound list.
---@param chars string? A string of characters to map the found sounds to. Each character in the string will be mapped to all found sounds. If nil or empty, maps found sounds to the generic "" key.
---@return self
---@see string.find
---@see sounds
---@see Sound
function Speech:addSoundSet(prefix, chars)
	local found = getAllSoundsMatchingPrefix(prefix)
	return self:addSound(chars and {[chars] = found} or found)
end

--- Registers a phrase to play a sound.
---@param sound SpeechSound The sound to register to this phrase.
---@param phrase string The phoneme or phrase to map the sound to.
---@return self
function Speech:registerPhrase(sound, phrase)
	if type(sound) ~= 'string' and type(sound) ~= 'Sound' then
		error('registerPhrase(): illegal sound argument: "'..tostring(sound)..'"')
		return self
	end
	if type(phrase) ~= 'string' then
		error('registerPhrase(): illegal phrase argument: "'..tostring(phrase)..'"')
		return self
	end
	if type(sound) == 'string' then
		local s = sounds[sound]
		if type(s) ~= 'Sound' then error('registerPhrase(): Sound "'..tostring(s)..'" is not a sound resource or string.') return self end
		sound = s
	end
	phrase = phrase:lower()
	if #phrase < 2 then
		error('registerPhrase(): phrase "'..phrase..'" is too short! Minimum length is 2 characters.')
		return self
	end
	if #phrase > MAX_PHRASE_LENGTH then	
		error('registerPhrase(): phrase "'..phrase..'" is too long! Maximum length is '..MAX_PHRASE_LENGTH..' characters.')
		return self
	end
	if not self.phrases[phrase] then self.phrases[phrase] = {} end
	table.insert(self.phrases[phrase], sound)

	return self
end

--- Registers a phrase to play one or more sounds.
---@param sound SpeechSound|SpeechSoundList The sound(s) to register to this phrase. 
---@param phrase string The phoneme or phrase to map the sound to.
---@return self
function Speech:addPhrase(sound, phrase)
	if type(sound) == 'string' or type(sound) == 'Sound' then
		self:registerPhrase(sound, phrase)
	elseif type(sound) == 'table' then
		for _, s in pairs(sound) do
			self:registerPhrase(s, phrase)
		end
	else
		error('addPhrase(): illegal sound argument: "'..tostring(sound)..'"')
		return self
	end
	return self
end

--- Registers phrases to play one or more sounds.
---@param phrases SpeechSoundMap the 
---@return self
function Speech:addPhrases(phrases)
	if type(phrases) ~= 'table' then
		error('addPhrases(): illegal phrases argument: "'..tostring(phrases)..'"')
		return self
	end
	for phrase, sound in pairs(phrases) do
		if type(phrase) ~= 'string' then
			error('addPhrases(): illegal phrase argument: "'..tostring(phrase)..'"')
			return self
		end
		self:addPhrase(sound, phrase)
	end
	return self
end

---Add one or more sounds from the custom sound list using a `prefix`.
---@param prefix string The prefix to search for in the custom sound list.
---@param phrase string? A string of characters to map the found sounds to. Each character in the string will be mapped to all found sounds. If nil or empty, maps found sounds to the generic "" key.
---@return self
---@see string.find
---@see sounds
---@see Sound
function Speech:addPhraseSet(prefix, phrase)
	return self:addPhrase(getAllSoundsMatchingPrefix(prefix), phrase)
end

---Clears the sound queue.
---@return self
function Speech:clearQueue() self.queue = {} return self end
---Stops currently playing sound and clears the queue.
---@return self
function Speech:stop() self:clearQueue() if self.currentSound then self.currentSound:stop() self.currentSound = nil end return self end
---Clears all sounds.
---@return self
function Speech:clearSounds() self:stop() self.sounds = {} return self end
---Clears all phrases.
---@return self
function Speech:clearPhrases() self:stop() self.phrases = {} return self end
---Clears all sounds and phrases.
---@return self
function Speech:clearAll() self:stop() self.sounds = {} self.phrases = {} return self end
---Sets the speech rate.
---@param rate? integer (Optional) The speech rate in ticks. If nil, sets rate to 1. Minimum is 1.
---@return self
function Speech:setRate(rate) self.rate = math.max(rate or 1, 1) return self end
---Sets the speech volume.
---@param volume? number (Optional) The volume. If nil, sets volume to 1. Maximum is 1.
---@return self
function Speech:setVolume(volume) self.volume = math.max(math.min(volume or 1, 1), 0) return self end
---Sets the base pitch.
---@param basePitch? number (Optional) The base pitch. If nil, sets base pitch to 1. Minimum is 0.1.
---@return self
function Speech:setBasePitch(basePitch) self.basePitch = math.max(basePitch or 1, 0.1) return self end
---Sets the pitch range.
---@param pitchRange? number (Optional) The pitch range. If nil, sets pitch range to 0.25. Minimum is 0, no random pitch change.
---@return self
function Speech:setPitchRange(pitchRange) self.pitchRange = math.max(pitchRange or 0.25, 0) return self end
---Sets the maximum speech length.
---@param maxLength? number (Optional) The maximum speech length. If nil, defaults to `SAFE_SPEECH_LENGTH` (64).
---@return self
function Speech:setMaxLength(maxLength) self.maxLength = math.max(math.min(maxLength, SAFE_SPEECH_LENGTH) or SAFE_SPEECH_LENGTH, 1) return self end
---Sets the maximum speech length to 1, so only one character per message.
---@return self
---@see Speech.setMaxLength
function Speech:setOneShot() return self:setMaxLength(1) end
---Sets if polyphony is enabled.
---@param polyphony? boolean (Optional) Polyphony. If true, sounds can play on top of eachother. If false, only one sound can play at a time. If nil, disables polyphony.
---@return self
function Speech:setPolyphony(polyphony) self.polyphony = polyphony or false return self end
---Sets the subtitle verb for the sound. Default is 'speaks': '<Player Name> speaks'
---@param verb? string (Optional) The subtitle verb. If nil, disables subtitles.
---@return self
function Speech:setSubtitleVerb(verb) self.subtitleVerb = verb return self end
---Sets if the speech should pause on spaces.
---@param spacesPause? boolean (Optional) If true, pause for self.rate ticks whenever spaces are encountered. If false, ignore spaces. If nil, defaults to true.
---@return self
function Speech:setSpacesPause(spacesPause) self.spacesPause = spacesPause ~= nil and spacesPause or true return self end
---Sets if the speech should detect `/tell`, `/msg` and `/w` commands.
---@param tellEnabled? boolean (Optional) If true, `/tell`, `/msg`, and `/w` commands trigger speech. If false, disables speech for `/tell`. If nil, defaults to true.
---@return self
function Speech:setTellEnabled(tellEnabled) self.tellEnabled = tellEnabled ~= nil and tellEnabled or true return self end
---Sets if Speech:play should append or replace the queue.
---@param append? boolean (Optional) If true, Speech:play will append new messages to the queue. If false, Speech:play clears all speech before playing. If nil, defaults to true.
---@return self
function Speech:setAppend(append) self.append = append ~= nil and append or true return self end
---Sets up a callback function that runs whenever a speech sound is played. Can be used for custom visualizers or other effects.
---@param callback? Speech.SpeechCallback The callback function. It will be passed the character that was spoken and the sound that was played.
---@return self
function Speech:setCallback(callback) self.speechCallback = callback return self end
---Queues up speech blips to play.
---@param msg? string (Optional) The message to play. If nil, queues 1 blip.
---@return self
function Speech:play(msg)
	local toSpeak = self:tokenize(msg) 
	if self.append then
		for _,s in ipairs(toSpeak) do table.insert(self.queue, s) end
	else
		self.queue = toSpeak
	end
	while #self.queue >= SAFE_SPEECH_LENGTH do
		table.remove(self.queue, 1)
	end
	return self
end

---Tokenizes a string into a list of phrases and characters, based on the registered phrases and characters.
---@param msg string The message to tokenize.
---@return string[] tokens The list of tokens.
---@private
---@see Speech.phrases
---@see Speech.sounds
function Speech:tokenize(msg)
	local tokens = {}
	local text = (msg:lower() or ''):sub(1,self.maxLength)

	local i = 1
	while i <= #text do
		local matched = false

		-- Phrase mapping (longest-match tokenizer)
		if self.phrases then
			for phrase in pairs(self.phrases) do
				if text:sub(i, i + #phrase - 1) == phrase then
					table.insert(tokens, phrase)
					i = i + #phrase
					matched = true
					break
				end
			end
		end

		-- Character mapping
		if not matched then
			table.insert(tokens, text:sub(i, i))
			i = i + 1
		end
	end

	if text == '' then
		table.insert(tokens, '')
	end

	return tokens
end

---Returns a randomized pitch for playing the speech sound.
---@return number pitch A randomized pitch from this speech object.
---@see Speech.basePitch
---@see Speech.pitchRange
---@private
function Speech:rollSpeechPitch()
	if (self.pitchRange or 0) > 0 then
		local basePitch = (self.basePitch or 1) - (self.pitchRange / 2)
		return basePitch + math.random() * self.pitchRange
	else
		return self.basePitch or 1
	end
end

---Plays a randomized speech sound.
---@param token string? (Optional) The character/phrase to play a sound for. If nil, plays a random sound from the generic list.
---@return Sound sound Tthe sound that was played, or nil if no sound was played.
function Speech:playSpeechSound(token)
	if not self.polyphony and self.currentSound then
		self.currentSound:stop()
	end
	local list
	if type(token) == 'string' then
		if #token == 1 then
			list = self.sounds[token] or (self.sounds[''] or {})
		elseif #token > 1 then
			list = self.phrases[token]
		end
	else
		list = self.sounds[''] or {}
	end
	if not list or #list < 1 and token then return nil end
	self.currentSound = list[math.random(#list)]
		:pos(player:getPos())
		:volume(self.volume)
		:pitch(self:rollSpeechPitch())
		:subtitle(self.subtitleVerb and (player:getName()..' '..self.subtitleVerb) or nil)
		:play()
	return self.currentSound
end

---The function that ticks this speech object.
function Speech:tick()
	if self.queue and #self.queue > 0 and world.getTime() % self.rate == 0 then
		local tok = table.remove(self.queue, 1)
		if tok ~= ' ' or (not self.spacesPause) then
			local snd = self:playSpeechSound(tok)
			if self.speechCallback then
				self.speechCallback(tok, snd)
			end
		end
	end
end

---Simple split based upon `string.gmatch`.
---@param str string The string to split.
---@param sep string? (Optional) The separator to split the string with. Defaults to `%s` (all whitespace).
---@return string[] split
local function matchSplit(str, sep)
	if sep == nil then sep = '%s' end
	local t = {}
	for s in string.gmatch(str, '([^'..sep..']+)') do
		table.insert(t, s)
	end
	return t
end

---Parses an input message, returns `nil` if not a valid BugSpeak message. (i.e. not a chat message)
---@param msg string The input message.
---@param tellEnabled boolean? (Optional) Whether or allow /msg, /tell, or /w commands.
---@return string|nil msg The spoken message, or `nil` if the message should not be spoken.
local function parseMessage(msg, tellEnabled)
	if type(msg) ~= 'string' or #msg == 0 then return nil end
	if msg:find('^/') then
		msg = msg:sub(2) -- trim command slash
		local cmd = matchSplit(msg, '%s')
		if #cmd <= 1 then return nil end
		if cmd[1] == 'say' then
			msg = table.concat(cmd, ' ', 2)
		elseif (cmd[1] == 'msg'
			or cmd[1] == 'tell'
			or cmd[1] == 'w')
			and tellEnabled then 
			msg = table.concat(cmd, ' ', 3)
		else 
			msg = nil
		end
	end
	return msg
end

---Chat message event handler.
---@param msg string
---@return string msg
---@see events
function Speech:chat_send_message(msg)
	local m = msg
	if not self.sounds[''] 
		or (#self.sounds[''] < 1
		and #self.sounds == 1)
		and next(self.phrases) == nil then
		-- Le annoying but important warning message.
		error("BugSpeak: No sounds registered on active Speech object! Please register sounds using Speech:addSound(), Speech:addSoundSet(), or Speech:registerPhrase() before sending messages.")
		return msg
	end

	local spoken = parseMessage(msg, self.tellEnabled)
	if self.volume > 0 and spoken then
		pings.BugSpeak(spoken)
	end
	return msg
end

---@class BugSpeak
---@field Speech Speech Speech object definition.
---@field private INSTANCE Speech Currently active speech instance.
---@field private RunLater RunLater manuel's local RunLater library.
local BugSpeak = {RunLater = RunLater, Speech = Speech, INSTANCE = nil}

---Sets a given speech object to the active one.
---@param speech Speech? The speech to activate. If nil, disables speech.
---@return Speech? speech The speech argument, or nil if not provided.
function BugSpeak.activate(speech)
	if  BugSpeak.INSTANCE and BugSpeak.INSTANCE ~= speech then
		BugSpeak.INSTANCE:clearQueue()
	end
	BugSpeak.INSTANCE = speech
	return speech
end

---Deactivates the current speech object.
---@return Speech deactivated The deactivated speech object, or nil if none exists.
function BugSpeak.deactivate()
	local deactivated = BugSpeak.current()
	BugSpeak.activate(nil)
	return deactivated
end

---Returns true if an active speech object exists.
---@return boolean speechEnabled Is there an active speech object?
function BugSpeak.active()
	return BugSpeak.current() ~= nil
end

---Returns the current speech object.
---@return Speech speech The active speech object.
function BugSpeak.current()
	return BugSpeak.INSTANCE
end

---Creates a new speech objects AND activates it.
---@return Speech speech The new speech object.
function BugSpeak.new()
	return BugSpeak.activate(Speech.new())
end

--Register figura events--
events.TICK:register(BugSpeak.RunLater.tick)
events.TICK:register(function () if BugSpeak.active() then BugSpeak.current():tick() end end)

events.CHAT_SEND_MESSAGE:register(function(msg)
	if not msg then return end
	if BugSpeak.active() then return BugSpeak.current():chat_send_message(msg) end
	return msg
end)

--Register figura pings--
function pings.BugSpeak(msg)
	if BugSpeak.active() then BugSpeak.current():play(msg) end
end

return BugSpeak